# Generated by Django 2.0.13 on 2020-07-05 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matricula ')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='Cpf ')),
                ('rg', models.CharField(max_length=7, verbose_name='Rg ')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('dataNascimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='imagens/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('quantidadeLimite', models.IntegerField(verbose_name='Quantidade Limite')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('slide', models.CharField(max_length=100, verbose_name='Slide')),
                ('refeicao', models.CharField(max_length=100, verbose_name='Refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataReserva', models.DateTimeField()),
                ('dataConfirmacaoReserva', models.DateTimeField()),
                ('dataRetiradaPendecia', models.DateTimeField()),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeitorio.Refeicao')),
                ('usuarioPendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pendencia', to=settings.AUTH_USER_MODEL)),
                ('usuarioReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reserva', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('suap', models.CharField(max_length=30, verbose_name='Suap')),
                ('dataIngresso', models.DateTimeField(verbose_name='Data de Ingresso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRefeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('horaInicio', models.DateTimeField()),
                ('horaFim', models.DateTimeField()),
                ('horaInicioReserva', models.DateTimeField()),
                ('horaFimReserva', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeitorio.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refeitorio.Turno'),
        ),
        migrations.AddField(
            model_name='refeicao',
            name='tipoRefeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refeitorio.TipoRefeicao'),
        ),
        migrations.AddField(
            model_name='refeicao',
            name='usuarioCadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro', to=settings.AUTH_USER_MODEL),
        ),
    ]
